from .command import Command

from typing import Final

# Get commands.
MSP_IDENT:      Final[Command] = Command(100, '3BI')
MSP_STATUS:     Final[Command] = Command(101, '3HIB')
MSP_RAW_IMU:    Final[Command] = Command(102, '8h')
MSP_SERVO:      Final[Command] = Command(103, '16H')
MSP_MOTOR:      Final[Command] = Command(104, '16H')
MSP_RC:         Final[Command] = Command(105, '16H')
MSP_RAW_GPS:    Final[Command] = Command(106, '2B2I3H')
MSP_COMP_GPS:   Final[Command] = Command(107, '2HB')
MSP_ATTITUDE:   Final[Command] = Command(108, '3h')
MSP_ALTITUDE:   Final[Command] = Command(109, 'ih')
MSP_ANALOG:     Final[Command] = Command(110, 'B3H')
MSP_RC_TUNING:  Final[Command] = Command(111, '7B')
MSP_PID:        Final[Command] = Command(112, '30B')
MSP_BOX:        Final[Command] = Command(113, '*H')
MSP_MISC:       Final[Command] = Command(114, '6HIH4B')
MSP_MOTOR_PINS: Final[Command] = Command(115, '8B')
MSP_BOXNAMES:   Final[Command] = Command(116, '*s')
MSP_PIDNAMES:   Final[Command] = Command(117, '*s')
MSP_WP:         Final[Command] = Command(118, 'B3I2HB')
MSP_BOXIDS:     Final[Command] = Command(119, '*3HB')
MSP_SERVO_CONF: Final[Command] = Command(120, '3HB' * 8)

# Set commands.
MSP_SET_RAW_RC:      Final[Command] = Command(200, '16H')
MSP_SET_RAW_GPS:     Final[Command] = Command(201, '2B2I2H')
MSP_SET_PID:         Final[Command] = Command(202, '30B')
MSP_SET_BOX:         Final[Command] = Command(203, '*H')
MSP_SET_RC_TUNING:   Final[Command] = Command(204, '7B')
MSP_ACC_CALIBRATION: Final[Command] = Command(205, None)
MSP_MAG_CALIBRATION: Final[Command] = Command(206, None)
MSP_SET_MISC:        Final[Command] = Command(207, '6HIH4B')
MSP_RESET_CONF:      Final[Command] = Command(208, None)
MSP_SET_WP:          Final[Command] = Command(209, 'B3I2HB')
MSP_SELECT_SETTING:  Final[Command] = Command(210, 'B')
MSP_SET_HEAD:        Final[Command] = Command(211, 'h')
MSP_SET_SERVO_CONF:  Final[Command] = Command(212, '3HB' * 8)
MSP_SET_MOTOR:       Final[Command] = Command(214, '16H')
MSP_BIND:            Final[Command] = Command(240, None)
MSP_EEPROM_WRITE:    Final[Command] = Command(250, None)
