from .msp_command import MspCommand

from typing import Final

# Get commands.
MSP_IDENT:      Final[MspCommand] = MspCommand(100, '3BI')
MSP_STATUS:     Final[MspCommand] = MspCommand(101, '3HIB')
MSP_RAW_IMU:    Final[MspCommand] = MspCommand(102, '8h')
MSP_SERVO:      Final[MspCommand] = MspCommand(103, '16H')
MSP_MOTOR:      Final[MspCommand] = MspCommand(104, '16H')
MSP_RC:         Final[MspCommand] = MspCommand(105, '16H')
MSP_RAW_GPS:    Final[MspCommand] = MspCommand(106, '2B2I3H')
MSP_COMP_GPS:   Final[MspCommand] = MspCommand(107, '2HB')
MSP_ATTITUDE:   Final[MspCommand] = MspCommand(108, '3h')
MSP_ALTITUDE:   Final[MspCommand] = MspCommand(109, 'ih')
MSP_ANALOG:     Final[MspCommand] = MspCommand(110, 'B3H')
MSP_RC_TUNING:  Final[MspCommand] = MspCommand(111, '7B')
MSP_PID:        Final[MspCommand] = MspCommand(112, '30B')
MSP_BOX:        Final[MspCommand] = MspCommand(113, '*16H')
MSP_MISC:       Final[MspCommand] = MspCommand(114, '6HIH4B')
MSP_MOTOR_PINS: Final[MspCommand] = MspCommand(115, '8B')
MSP_BOXNAMES:   Final[MspCommand] = MspCommand(116, '*s')
MSP_PIDNAMES:   Final[MspCommand] = MspCommand(117, '*s')
MSP_WP:         Final[MspCommand] = MspCommand(118, 'B3I2HB')
MSP_BOXIDS:     Final[MspCommand] = MspCommand(119, '*3HB')
MSP_SERVO_CONF: Final[MspCommand] = MspCommand(120, '3HB' * 8)

# Set commands.
MSP_SET_RAW_RC:      Final[MspCommand] = MspCommand(200, '16H')
MSP_SET_RAW_GPS:     Final[MspCommand] = MspCommand(201, '2B2I2H')
MSP_SET_PID:         Final[MspCommand] = MspCommand(202, '30B')
MSP_SET_BOX:         Final[MspCommand] = MspCommand(203, '*16H')
MSP_SET_RC_TUNING:   Final[MspCommand] = MspCommand(204, '7B')
MSP_ACC_CALIBRATION: Final[MspCommand] = MspCommand(205, None)
MSP_MAG_CALIBRATION: Final[MspCommand] = MspCommand(206, None)
MSP_SET_MISC:        Final[MspCommand] = MspCommand(207, '6HIH4B')
MSP_RESET_CONF:      Final[MspCommand] = MspCommand(208, None)
MSP_SET_WP:          Final[MspCommand] = MspCommand(209, 'B3I2HB')
MSP_SELECT_SETTING:  Final[MspCommand] = MspCommand(210, 'B')
MSP_SET_HEAD:        Final[MspCommand] = MspCommand(211, 'h')
MSP_SET_SERVO_CONF:  Final[MspCommand] = MspCommand(212, '3HB' * 8)
MSP_SET_MOTOR:       Final[MspCommand] = MspCommand(214, '16H')
MSP_BIND:            Final[MspCommand] = MspCommand(240, None)
MSP_EEPROM_WRITE:    Final[MspCommand] = MspCommand(250, None)
